apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: sa-pod-reader
    namespace: development
subjects:
    - kind: ServiceAccount
      name: my-serviceaccount 
      namespace: development
roleRef:
  kind: Role 
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io